name: Update links

on:
  schedule:
    - cron: "0 */4 * * *"
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup folder
        run: |
          mkdir -p links

      - name: Get links
        id: get_links
        run: |
          echo "Getting arknights link..."
          ak_link=`curl -Ls -r 0-0 -o /dev/null -w %{url_effective} https://ak.hypergryph.com/downloads/android_lastest`
          echo "ak_link=$ak_link" | tee -a $GITHUB_OUTPUT

          echo "Getting endfield link..."
          ef_link=`curl -Ls -r 0-0 -o /dev/null -w %{url_effective} https://launcher.hypergryph.com/game/latest/6LL0KJuqHBVz33WK/1/1`
          echo "ef_link=$ef_link" | tee -a $GITHUB_OUTPUT

          echo "Getting skland link..."
          sk_link=`curl -s --header 'Origin: https://www.skland.com' https://assets.skland.com/common-config/json/app-config.json | \
            jq -r ".downloadUrl.android"`
          echo "sk_link=$sk_link" | tee -a $GITHUB_OUTPUT

      - name: Update links
        run: |
          endfield_timestamp=$(grep -oP 'Endfield date]\(https:\/\/img\.shields\.io\/date\/\K\d+' README.md)
          cp README-template.md README.md

          if diff links/arknights <(echo ${{ steps.get_links.outputs.ak_link }}) &> /dev/null; then
            echo "No update needed for arknights link."
            sed -i "s|{{arknights_timestamp}}|$(git log -1 --pretty=%ct links/arknights)|" README.md
          else
            echo "Updating arknights link..."
            echo ${{ steps.get_links.outputs.ak_link }} > links/arknights
            sed -i "s|{{arknights_timestamp}}|$(date +%s)|" README.md
          fi
          sed -i "s|{{arknights_link}}|$(cat links/arknights)|" README.md

          ef_link_regex='^[^_]*_\K[^/]+'
          if [[ $(grep -m 1 -oP "$ef_link_regex" links/endfield) == $(echo ${{ steps.get_links.outputs.ef_link }} | grep -m 1 -oP "$ef_link_regex") ]]; then
            if [[ $(curl -s -o /dev/null -w "%{http_code}" $(cat links/endfield)) = 403 ]]; then
              echo "Updating auth_key..."
              echo ${{ steps.get_links.outputs.ef_link }} > links/endfield
              sed -i "s|{{endfield_authkey_timestamp}}|$(date +%s)|" README.md
            else
              echo "No update needed for endfield link."
            fi
            sed -i "s|{{endfield_timestamp}}|$endfield_timestamp|" README.md
          else
            echo "Updating endfield link..."
            echo ${{ steps.get_links.outputs.ef_link }} > links/endfield
            sed -i "s|{{endfield_timestamp}}|$(date +%s)|" README.md
            sed -i "s|{{endfield_authkey_timestamp}}|$(date +%s)|" README.md
          fi
          sed -i "s|{{endfield_link}}|$(cat links/endfield)|" README.md

          if diff links/skland <(echo ${{ steps.get_links.outputs.sk_link }}) &> /dev/null; then
            echo "No update needed for skland link."
            sed -i "s|{{skland_timestamp}}|$(git log -1 --pretty=%ct links/skland)|" README.md
          else
            echo "Updating skland link..."
            echo ${{ steps.get_links.outputs.sk_link }} > links/skland
            sed -i "s|{{skland_timestamp}}|$(date +%s)|" README.md
          fi
          sed -i "s|{{skland_link}}|$(cat links/skland)|" README.md

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
