name: Update links

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup folder
        run: |
          mkdir -p links

      - name: Get links
        run: |
          echo "Getting arknights link..."
          curl -sI https://ak.hypergryph.com/downloads/android_lastest |grep -m 1 -oE "https://ak.hycdn.cn/apk/.*\.apk" > links/arknights || exit 1
          cat links/arknights
          echo "Getting skland link..."
          curl -s --header 'Origin: https://www.skland.com' https://assets.skland.com/common-config/json/app-config.json | jq -r ".downloadUrl.android" > links/skland || exit 1
          cat links/skland
      
      - name: Update links
        run: |
          cp README-template.md README.md
          sed -i "s|{{timestamp}}|$(date +%s)|" README.md
          sed -i "s|{{arknights_link}}|$(cat links/arknights)|" README.md
          sed -i "s|{{skland_link}}|$(cat links/skland)|" README.md
      
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5

      
